CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS postgres_fdw;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
GRANT USAGE ON FOREIGN DATA WRAPPER postgres_fdw TO "graph-node";
